### ISSUE TITLE
Comments re labeling guidance - month 

### ISSUE THREAD

**Issue by michaelhofrichter** [SuffolkLITLab/doc-assembly-line#7]
Is `incident_date_month` equivalent to `March` or `3`?

@plocket replied: 

> I also wasn’t sure how to do this. [Again, I had hoped that `date` implied numbers, but maybe that’s not effective. For name,] maybe `x_date_name_month`? To that end, should numbered date conventions be `x_date_number_month` and `x_date_number_day_month`? Should the rule for `March 3rd` be `x_date_name_month_number_day`? Maybe the whole rule needs to be more formulaic, even though it makes it long`: x_date_name_month_nth_day_4_digit_year`, `x_date_number_day_number_month_2_digit_year`? Thoughts?

I think `x_date_month_number` and `x_date_month_name` make the most sense. Go from general to specific -- `month` then number/name. Or just state that all dates are numeric unless `_name` is appended at the end. I wouldn't try to get complicated with the long versions, because anyplace that asks for that would be a long blank and we can just drop in `5/15/2020` and that should suffice.

**Comment by plocket** [comment]
How about just `x_month_number` and `x_month_name`, @michaelhofrichterHVL ?

**Comment by plocket** [comment]
Hmm, maybe that would make the parsing harder. Not sure. I think people are going to make a ton of mistakes with these dates, though. They're so specific.

**Comment by michaelhofrichter** [comment]
I think having date in the name helps us when we're coding to plug in the date format. It also lets us just filter variables for something that includes `_date_` to make sure it has the right formatting. But you're the one creating the code behind parsing, so...

**Comment by plocket** [comment]
The word `_date_` would definitely help with parsing, as long as folks actually use it. It's worth trying, though.

**Comment by plocket** [comment]
From docassemble Slack #assembly-line:
> ...the dateutil.parser.parse() python function does a very good job of taking odd date variations in string form and compiling them into the appropriate datetime object format (which itself lets you extract out month, year, day or week, etc as needed) Eliminates the need to create a logic path for such things.

**Comment by plocket** [comment]
I have very partially implemented this - specifically for the `_digit_year` conventions. I'd still like to hear from @nonprofittechy about which ones of these should be adopted.
