### ISSUE TITLE
Comments re labeling guidance -- multiple individual's characteristics

### ISSUE THREAD

**Issue by michaelhofrichter** [SuffolkLITLab/doc-assembly-line#8]
I asked:

> For `plaintiff__2` do I use `plaintiff__2_age`? And then if I have to use it in two places, it would be `plaintiff__2_age__2`?

@plocket replied:

> That is such an excellent point! We definitely need to add an example like that! Just so the knowledge doesn’t get lost - it would be `plaintiff_age__2`. I’m not sure how to describe that in words. It’s the field name as it appeared the first time, plus `__n`, with a unique number. I’ll make that change right off.

But I'm not sure that I agree. What if we have a form that asks for the plaintiff's age twice that also has two plaintiffs (I'm thinking grandparent visitation/kinship forms). Then the first time for the grandmother would be `plaintiff_age` and the second would be `plaintiff_age__2`, but then the ages for grandmother would be `plaintiff_age__2` and `plaintiff_age__2__2`? I think you'd have to do `plaintiff__2_age` and `plaintiff__2_age__2` to keep everything straight. Another example might be in a list of children that are subject to the court order.

**Comment by plocket** [comment]
If there were two plaintiffs with ages:
```
plaintiff1_age
plaintiff2_age
```

If those values were needed for a second time each:

```
plaintiff1_age__2
plaintiff2_age__2
```

Does that clarify, or am I not understanding the question? If it doesn't cover it, can you give me a more specific example, as I laid out above, @michaelhofrichterHVL ?

**Comment by michaelhofrichter** [comment]
Thanks @plocket. That helps. I got the way to have a second Individual wrong. However, the guide doesn't have any instruction about how to label if there is a second individual with that role (i.e. `plaintiff` vs. `plaintiff2`). That should get added.

**Comment by plocket** [comment]
You're completely right. That's the part that my brain was too fried to rearrange at the time. Right now it says to ask in Slack. It's the part that's coming next 👍

**Comment by plocket** [comment]
Won't close this issue till it's there!

**Comment by plocket** [comment]
How's this: https://github.com/SuffolkLITLab/doc-assembly-line/blob/labeling-doc/pdf-label-names.md#more-than-one

**Comment by plocket** [comment]
For now, we've merged the branch. Feel free to add thoughts on the outcome, though.

**Comment by KidPluto** [comment]
> How's this: https://github.com/SuffolkLITLab/doc-assembly-line/blob/labeling-doc/pdf-label-names.md#more-than-one

That gives me a 404

**Comment by KidPluto** [comment]
Maybe this one?
https://github.com/SuffolkLITLab/doc-assembly-line/blob/master/labeling-pdf-fields.md

**Comment by plocket** [comment]
Sorry, @KidPluto , too many notifications in life. That looks like the correct one.
